INSERT INTO system_attacks(name, type, power, pp, speed, accuracy, target, damage_type, description)
VALUES ("pound",1,40,35,0,100,10,2,"The target is physically pounded with a long tail or a foreleg, etc."),
("karate chop",2,50,25,0,100,10,2,"The target is attacked with a sharp chop. Critical hits land more easily."),
("doubleslap",1,15,10,0,85,10,2,"The target is slapped repeatedly, back and forth, two to five times in a row."),
("comet punch",1,18,15,0,85,10,2,"The target is hit with a flurry of punches that strike two to five times in a row."),
("mega punch",1,80,20,0,85,10,2,"The target is slugged by a punch thrown with muscle-packed power."),
("pay day",1,40,20,0,100,10,2,"Numerous coins are hurled at the target to inflict damage. Money is earned after the battle."),
("fire punch",10,75,15,0,100,10,2,"The target is punched with a fiery fist. It may also leave the target with a burn."),
("ice punch",15,75,15,0,100,10,2,"The target is punched with an icy fist. It may also leave the target frozen."),
("thunderpunch",13,75,15,0,100,10,2,"The target is punched with an electrified fist. It may also leave the target with paralysis."),
("scratch",1,40,35,0,100,10,2,"Hard, pointed, and sharp claws rake the target to inflict damage."),
("vicegrip",1,55,30,0,100,10,2,"The target is gripped and squeezed from both sides to inflict damage."),
("guillotine",1,1,5,0,30,10,2,"A vicious, tearing attack with big pincers. The target will faint instantly if this attack hits."),
("razor wind",1,80,10,0,100,11,3,"A two-turn attack. Blades of wind hit opposing Pokémon on the second turn. Critical hits land more easily."),
("swords dance",1,0,30,0,0,7,1,"A frenetic dance to uplift the fighting spirit. It sharply raises the user's Attack stat."),
("cut",1,50,30,0,95,10,2,"The target is cut with a scythe or a claw. It can also be used to cut down thin trees."),
("gust",3,40,35,0,100,10,3,"A gust of wind is whipped up by wings and launched at the target to inflict damage."),
("wing attack",3,60,35,0,100,10,2,"The target is struck with large, imposing wings spread wide to inflict damage."),
("whirlwind",1,0,20,-6,100,10,1,"The target is blown away and switched. In the wild, a battle against a single Pokémon ends."),
("fly",3,90,15,0,95,10,2,"The user soars, then strikes its target on the second turn. It can also be used for flying to any familiar town."),
("bind",1,15,20,0,85,10,2,"Things such as long bodies or tentacles are used to bind and squeeze the target for four to five turns."),
("slam",1,80,20,0,75,10,2,"The target is slammed with a long tail, vines, etc., to inflict damage."),
("vine whip",12,35,15,0,100,10,2,"The target is struck with slender, whiplike vines to inflict damage."),
("stomp",1,65,20,0,100,10,2,"The target is stomped with a big foot. It may also make the target flinch."),
("double kick",2,30,30,0,100,10,2,"The target is quickly kicked twice in succession using both feet."),
("mega kick",1,120,5,0,75,10,2,"The target is attacked by a kick launched with muscle-packed power."),
("jump kick",2,100,10,0,95,10,2,"The user jumps up high, then strikes with a kick. If the kick misses, the user hurts itself."),
("rolling kick",2,60,15,0,85,10,2,"The user lashes out with a quick, spinning kick. It may also make the target flinch."),
("sand attack",5,0,15,0,100,10,1,"Sand is hurled in the target's face, reducing its accuracy."),
("headbutt",1,70,15,0,100,10,2,"The user sticks out its head and attacks by charging straight into the target. It may also make the target flinch."),
("horn attack",1,65,25,0,100,10,2,"The target is jabbed with a sharply pointed horn to inflict damage."),
("fury attack",1,15,20,0,85,10,2,"The target is jabbed repeatedly with a horn or beak two to five times in a row."),
("horn drill",1,1,5,0,30,10,2,"The user stabs the target with a horn that rotates like a drill. If it hits, the target faints instantly."),
("tackle",1,50,35,0,100,10,2,"A physical attack in which the user charges and slams into the target with its whole body."),
("body slam",1,85,15,0,100,10,2,"The user drops onto the target with its full body weight. It may also leave the target with paralysis."),
("wrap",1,15,20,0,90,10,2,"A long body or vines are used to wrap and squeeze the target for four to five turns."),
("take down",1,90,20,0,85,10,2,"A reckless, full-body charge attack for slamming into the target. It also damages the user a little."),
("thrash",1,120,10,0,100,8,2,"The user rampages and attacks for two to three turns. It then becomes confused, however."),
("double edge",1,120,15,0,100,10,2,"A reckless, life-risking tackle. It also damages the user by a fairly large amount, however."),
("tail whip",1,0,30,0,100,11,1,"The user wags its tail cutely, making opposing Pokémon less wary and lowering their Defense stat."),
("poison sting",4,15,35,0,100,10,2,"The user stabs the target with a poisonous stinger. This may also poison the target."),
("twineedle",7,25,20,0,100,10,2,"The user damages the target twice in succession by jabbing it with two spikes. It may also poison the target."),
("pin missile",7,14,20,0,85,10,2,"Sharp spikes are shot at the target in rapid succession. They hit two to five times in a row."),
("leer",1,0,30,0,100,11,1,"The user gains an intimidating leer with sharp eyes. The opposing team's Defense stats are reduced."),
("bite",17,60,25,0,100,10,2,"The target is bitten with viciously sharp fangs. It may make the target flinch."),
("growl",1,0,40,0,100,11,1,"The user growls in an endearing way, making the opposing team less wary. The foes' Attack stats are lowered."),
("roar",1,0,20,-6,100,10,1,"The target is scared off and switched. In the wild, a battle against a single Pokémon ends."),
("sing",1,0,15,0,55,10,1,"A soothing lullaby is sung in a calming voice that puts the target into a deep slumber."),
("supersonic",1,0,20,0,55,10,1,"The user generates odd sound waves from its body. It may confuse the target."),
("sonicboom",1,1,20,0,90,10,3,"The target is hit with a destructive shock wave that always inflicts 20 HP damage."),
("disable",1,0,20,0,100,10,1,"For four turns, this move prevents the target from using the move it last used."),
("acid",4,40,30,0,100,11,3,"The opposing team is attacked with a spray of harsh acid. The acid may also lower the targets' Sp. Def stats."),
("ember",10,40,25,0,100,10,3,"The target is attacked with small flames. It may also leave the target with a burn."),
("flamethrower",10,95,15,0,100,10,3,"The target is scorched with an intense blast of fire. It may also leave the target with a burn."),
("mist",15,0,30,0,0,4,1,"The user cloaks its body with a white mist that prevents any of its stats from being cut for five turns."),
("water gun",11,40,25,0,100,10,3,"The target is blasted with a forceful shot of water."),
("hydro pump",11,120,5,0,80,10,3,"The target is blasted by a huge volume of water launched under great pressure."),
("surf",11,95,15,0,100,9,3,"It swamps the area around the user with a giant wave. It can also be used for crossing water."),
("ice beam",15,95,10,0,100,10,3,"The target is struck with an icy-cold beam of energy. It may also freeze the target solid."),
("blizzard",15,120,5,0,70,11,3,"A howling blizzard is summoned to strike the opposing team. It may also freeze them solid."),
("psybeam",14,65,20,0,100,10,3,"The target is attacked with a peculiar ray. It may also cause confusion."),
("bubblebeam",11,65,20,0,100,10,3,"A spray of bubbles is forcefully ejected at the opposing team. It may also lower their Speed stats."),
("aurora beam",15,65,20,0,100,10,3,"The target is hit with a rainbow-colored beam. This may also lower the target's Attack stat."),
("hyper beam",1,150,5,0,90,10,3,"The target is attacked with a powerful beam. The user must rest on the next turn to regain its energy."),
("peck",3,35,35,0,100,10,2,"The target is jabbed with a sharply pointed beak or horn."),
("drill peck",3,80,20,0,100,10,2,"A corkscrewing attack with the sharp beak acting as a drill."),
("submission",2,80,25,0,80,10,2,"The user grabs the target and recklessly dives for the ground. It also hurts the user slightly."),
("low kick",2,1,20,0,100,10,2,"A powerful low kick that makes the target fall over. It inflicts greater damage on heavier targets."),
("counter",2,1,20,-5,100,1,2,"A retaliation move that counters any physical attack, inflicting double the damage taken."),
("seismic toss",2,1,20,0,100,10,2,"The target is thrown using the power of gravity. It inflicts damage equal to the user's level."),
("strength",1,80,15,0,100,10,2,"The target is slugged with a punch thrown at maximum power. It can also be used to move heavy boulders."),
("absorb",12,20,25,0,100,10,3,"A nutrient-draining attack. The user's HP is restored by half the damage taken by the target."),
("mega drain",12,40,15,0,100,10,3,"A nutrient-draining attack. The user's HP is restored by half the damage taken by the target."),
("leech seed",12,0,10,0,90,10,1,"A seed is planted on the target. It steals some HP from the target every turn."),
("growth",1,0,40,0,0,7,1,"The user's body grows all at once, raising the Attack and Sp. Atk stats."),
("razor leaf",12,55,25,0,95,11,2,"Sharp-edged leaves are launched to slash at the opposing team. Critical hits land more easily."),
("solarbeam",12,120,10,0,100,10,3,"A two-turn attack. The user gathers light, then blasts a bundled beam on the second turn."),
("poisonpowder",4,0,35,0,75,10,1,"The user scatters a cloud of poisonous dust on the target. It may poison the target."),
("stun spore",12,0,30,0,75,10,1,"The user scatters a cloud of paralyzing powder. It may leave the target with paralysis."),
("sleep powder",12,0,15,0,75,10,1,"The user scatters a big cloud of sleep-inducing dust around the target."),
("petal dance",12,120,10,0,100,8,3,"The user attacks the target by scattering petals for two to three turns. The user then becomes confused."),
("string shot",7,0,40,0,95,11,1,"The targets are bound with silk blown from the user's mouth. This silk reduces the targets' Speed stat."),
("dragon rage",16,1,10,0,100,10,3,"This attack hits the target with a shock wave of pure rage. This attack always inflicts 40 HP damage."),
("fire spin",10,35,15,0,85,10,3,"The target becomes trapped within a fierce vortex of fire that rages for four to five turns."),
("thundershock",13,40,30,0,100,10,3,"A jolt of electricity is hurled at the target to inflict damage. It may also leave the target with paralysis."),
("thunderbolt",13,95,15,0,100,10,3,"A strong electric blast is loosed at the target. It may also leave the target with paralysis."),
("thunder wave",13,0,20,0,100,10,1,"A weak electric charge is launched at the target. It causes paralysis if it hits."),
("thunder",13,120,10,0,70,10,3,"A wicked thunderbolt is dropped on the target to inflict damage. It may also leave the target with paralysis."),
("rock throw",6,50,15,0,90,10,2,"The user picks up and throws a small rock at the target to attack."),
("earthquake",5,100,10,0,100,9,2,"The user sets off an earthquake that strikes those around it."),
("fissure",5,1,5,0,30,10,2,"The user opens up a fissure in the ground and drops the target in. The target instantly faints if it hits."),
("dig",5,80,10,0,100,10,2,"The user burrows, then attacks on the second turn. It can also be used to exit dungeons."),
("toxic",4,0,10,0,90,10,1,"A move that leaves the target badly poisoned. Its poison damage worsens every turn."),
("confusion",14,50,25,0,100,10,3,"The target is hit by a weak telekinetic force. It may also leave the target confused."),
("psychic",14,90,10,0,100,10,3,"The target is hit by a strong telekinetic force. It may also reduce the target's Sp. Def stat."),
("hypnosis",14,0,20,0,60,10,1,"The user employs hypnotic suggestion to make the target fall into a deep sleep."),
("meditate",14,0,40,0,0,7,1,"The user meditates to awaken the power deep within its body and raise its Attack stat."),
("agility",14,0,30,0,0,7,1,"The user relaxes and lightens its body to move faster. It sharply boosts the Speed stat."),
("quick attack",1,40,30,1,100,10,2,"The user lunges at the target at a speed that makes it almost invisible. It is sure to strike first."),
("rage",1,20,20,0,100,10,2,"As long as this move is in use, the power of rage raises the Attack stat each time the user is hit in battle."),
("teleport",14,0,20,0,0,7,1,"Use it to flee from any wild Pokémon. It can also warp to the last Pokémon Center visited."),
("night shade",8,1,15,0,100,10,3,"The user makes the target see a frightening mirage. It inflicts damage matching the user's level."),
("mimic",1,0,10,0,0,10,1,"The user copies the target's last move. The move can be used during battle until the Pokémon is switched out."),
("screech",1,0,40,0,85,10,1,"An earsplitting screech harshly reduces the target's Defense stat."),
("double team",1,0,15,0,0,7,1,"By moving rapidly, the user makes illusory copies of itself to raise its evasiveness."),
("recover",1,0,10,0,0,7,1,"Restoring its own cells, the user restores its own HP by half of its max HP."),
("harden",1,0,30,0,0,7,1,"The user stiffens all the muscles in its body to raise its Defense stat."),
("minimize",1,0,20,0,0,7,1,"The user compresses its body to make itself look smaller, which sharply raises its evasiveness."),
("smokescreen",1,0,20,0,100,10,1,"The user releases an obscuring cloud of smoke or ink. It reduces the target's accuracy."),
("confuse ray",8,0,10,0,100,10,1,"The target is exposed to a sinister ray that triggers confusion."),
("withdraw",11,0,40,0,0,7,1,"The user withdraws its body into its hard shell, raising its Defense stat."),
("defense curl",1,0,40,0,0,7,1,"The user curls up to conceal weak spots and raise its Defense stat."),
("barrier",14,0,30,0,0,7,1,"The user throws up a sturdy wall that sharply raises its Defense stat."),
("light screen",14,0,30,0,0,4,1,"A wondrous wall of light is put up to suppress damage from special attacks for five turns."),
("haze",15,0,30,0,0,12,1,"The user creates a haze that eliminates every stat change among all the Pokémon engaged in battle."),
("reflect",14,0,20,0,0,4,1,"A wondrous wall of light is put up to suppress damage from physical attacks for five turns."),
("focus energy",1,0,30,0,0,7,1,"The user takes a deep breath and focuses so that critical hits land more easily."),
("bide",1,1,10,1,0,7,2,"The user endures attacks for two turns, then strikes back to cause double the damage taken."),
("metronome",1,0,10,0,0,7,1,"The user waggles a finger and stimulates its brain into randomly using nearly any move."),
("mirror move",3,0,20,0,0,10,1,"The user counters the target by mimicking the target's last move."),
("selfdestruct",1,200,5,0,100,9,2,"The user attacks everything around it by causing an explosion. The user faints upon using this move."),
("egg bomb",1,100,10,0,75,10,2,"A large egg is hurled at the target with maximum force to inflict damage."),
("lick",8,20,30,0,100,10,2,"The target is licked with a long tongue, causing damage. It may also leave the target with paralysis."),
("smog",4,20,20,0,70,10,3,"The target is attacked with a discharge of filthy gases. It may also poison the target."),
("sludge",4,65,20,0,100,10,3,"Unsanitary sludge is hurled at the target. It may also poison the target."),
("bone club",5,65,20,0,85,10,2,"The user clubs the target with a bone. It may also make the target flinch."),
("fire blast",10,120,5,0,85,10,3,"The target is attacked with an intense blast of all-consuming fire. It may also leave the target with a burn."),
("waterfall",11,80,15,0,100,10,2,"The user charges at the target and may make it flinch. It can also be used to climb a waterfall."),
("clamp",11,35,15,0,85,10,2,"The target is clamped and squeezed by the user's very thick and sturdy shell for four to five turns."),
("swift",1,60,20,0,0,11,3,"Star-shaped rays are shot at the opposing team. This attack never misses."),
("skull bash",1,100,15,0,100,10,2,"The user tucks in its head to raise its Defense in the first turn, then rams the target on the next turn."),
("spike cannon",1,20,15,0,100,10,2,"Sharp spikes are shot at the target in rapid succession. They hit two to five times in a row."),
("constrict",1,10,35,0,100,10,2,"The target is attacked with long, creeping tentacles or vines. It may also lower the target's Speed stat."),
("amnesia",14,0,20,0,0,7,1,"The user temporarily empties its mind to forget its concerns. It sharply raises the user's Sp. Def stat."),
("kinesis",14,0,15,0,80,10,1,"The user distracts the target by bending a spoon. It lowers the target's accuracy."),
("softboiled",1,0,10,0,0,7,1,"The user restores its own HP by up to half of its maximum HP. May also be used in the field to heal HP."),
("hi jump kick",2,130,10,0,90,10,2,"The target is attacked with a knee kick from a jump. If it misses, the user is hurt instead."),
("glare",1,0,30,0,90,10,1,"The user intimidates the target with the pattern on its belly to cause paralysis."),
("dream eater",14,100,15,0,100,10,3,"The user eats the dreams of a sleeping target. It absorbs half the damage caused to heal the user's HP."),
("poison gas",4,0,40,0,80,11,1,"A cloud of poison gas is sprayed in the face of opposing Pokémon. It may poison those hit."),
("barrage",1,15,20,0,85,10,2,"Round objects are hurled at the target to strike two to five times in a row."),
("leech life",7,20,15,0,100,10,2,"The user drains the target's blood. The user's HP is restored by half the damage taken by the target."),
("lovely kiss",1,0,10,0,75,10,1,"With a scary face, the user tries to force a kiss on the target. If it succeeds, the target falls asleep."),
("sky attack",3,140,5,0,90,10,2,"A second-turn attack move where critical hits land more easily. It may also make the target flinch."),
("transform",1,0,10,0,0,10,1,"The user transforms into a copy of the target right down to having the same move set."),
("bubble",11,20,30,0,100,11,3,"A spray of countless bubbles is jetted at the opposing team. It may also lower the targets' Speed stats."),
("dizzy punch",1,70,10,0,100,10,2,"The target is hit with rhythmically launched punches that may also leave it confused."),
("spore",12,0,15,0,100,10,1,"The user scatters bursts of spores that induce sleep."),
("flash",1,0,20,0,100,10,1,"The user flashes a bright light that cuts the target's accuracy. It can also be used to illuminate caves."),
("psywave",14,1,15,0,80,10,3,"The target is attacked with an odd psychic wave. The attack varies in intensity."),
("splash",1,0,40,0,0,7,1,"The user just flops and splashes around to no effect at all..."),
("acid armor",4,0,40,0,0,7,1,"The user alters its cellular structure to liquefy itself, sharply raising its Defense stat."),
("crabhammer",11,90,10,0,90,10,2,"The target is hammered with a large pincer. Critical hits land more easily."),
("explosion",1,250,5,0,100,9,2,"The user explodes to inflict damage on those around it. The user faints upon using this move."),
("fury swipes",1,18,15,0,80,10,2,"The target is raked with sharp claws or scythes for two to five times in quick succession."),
("bonemerang",5,50,10,0,90,10,2,"The user throws the bone it holds. The bone loops to hit the target twice, coming and going."),
("rest",14,0,10,0,0,7,1,"The user goes to sleep for two turns. It fully restores the user's HP and heals any status problem."),
("rock slide",6,75,10,0,90,11,2,"Large boulders are hurled at the opposing team to inflict damage. It may also make the targets flinch."),
("hyper fang",1,80,15,0,90,10,2,"The user bites hard on the target with its sharp front fangs. It may also make the target flinch."),
("sharpen",1,0,30,0,0,7,1,"The user reduces its polygon count to make itself more jagged, raising the Attack stat."),
("conversion",1,0,30,0,0,7,1,"The user changes its type to become the same type as one of its moves."),
("tri attack",1,80,10,0,100,10,3,"The user strikes with a simultaneous three-beam attack. May also burn, freeze, or leave the target with paralysis."),
("super fang",1,1,10,0,90,10,2,"The user chomps hard on the target with its sharp front fangs. It cuts the target's HP to half."),
("slash",1,70,20,0,100,10,2,"The target is attacked with a slash of claws or blades. Critical hits land more easily."),
("substitute",1,0,10,0,0,7,1,"The user makes a copy of itself using some of its HP. The copy serves as the user's decoy."),
("struggle",1,50,0,0,0,10,2,"An attack that is used in desperation only if the user has no PP. It also hurts the user slightly."),
("sketch",1,0,1,0,0,10,1,"It enables the user to permanently learn the move last used by the target. Once used, Sketch disappears."),
("triple kick",2,10,10,0,90,10,2,"A consecutive three-kick attack that becomes more powerful with each successive hit."),
("thief",17,40,10,0,100,10,2,"The user attacks and steals the target's held item simultaneously. It can't steal if the user holds an item."),
("spider web",7,0,10,0,0,10,1,"The user ensnares the target with thin, gooey silk so it can't flee from battle."),
("mind reader",1,0,5,0,0,10,1,"The user senses the target's movements with its mind to ensure its next attack does not miss the target."),
("nightmare",8,0,15,0,100,10,1,"A sleeping target sees a nightmare that inflicts some damage every turn."),
("flame wheel",10,60,25,0,100,10,2,"The user cloaks itself in fire and charges at the target. It may also leave the target with a burn."),
("snore",1,40,15,0,100,10,3,"An attack that can be used only if the user is asleep. The harsh noise may also make the target flinch."),
("curse",8,0,10,0,0,1,1,"A move that works differently for the Ghost type than for all other types."),
("flail",1,1,15,0,100,10,2,"The user flails about aimlessly to attack. It becomes more powerful the less HP the user has."),
("conversion 2",1,0,30,0,0,10,1,"The user changes its type to make itself resistant to the type of the attack the opponent used last."),
("aeroblast",3,100,5,0,95,10,3,"A vortex of air is shot at the target to inflict damage. Critical hits land more easily."),
("cotton spore",12,0,40,0,100,10,1,"The user releases cotton-like spores that cling to the target, harshly reducing its Speed stat."),
("reversal",2,1,15,0,100,10,2,"An all-out attack that becomes more powerful the less HP the user has."),
("spite",8,0,10,0,100,10,1,"The user unleashes its grudge on the move last used by the target by cutting 4 PP from it."),
("powder snow",15,40,25,0,100,11,3,"The user attacks with a chilling gust of powdery snow. It may also freeze the targets."),
("protect",1,0,10,4,0,7,1,"It enables the user to evade all attacks. Its chance of failing rises if it is used in succession."),
("mach punch",2,40,30,1,100,10,2,"The user throws a punch at blinding speed. It is certain to strike first."),
("scary face",1,0,10,0,100,10,1,"The user frightens the target with a scary face to harshly reduce its Speed stat."),
("faint attack",17,60,20,0,0,10,2,"The user approaches the target disarmingly, then throws a sucker punch. It hits without fail."),
("sweet kiss",1,0,10,0,75,10,1,"The user kisses the target with a sweet, angelic cuteness that causes confusion."),
("belly drum",1,0,10,0,0,7,1,"The user maximizes its Attack stat in exchange for HP equal to half its max HP."),
("sludge bomb",4,90,10,0,100,10,3,"Unsanitary sludge is hurled at the target. It may also poison the target."),
("mud slap",5,20,10,0,100,10,3,"The user hurls mud in the target's face to inflict damage and lower its accuracy."),
("octazooka",11,65,10,0,85,10,3,"The user attacks by spraying ink in the target's face or eyes. It may also lower the target's accuracy."),
("spikes",5,0,20,0,0,6,1,"The user lays a trap of spikes at the opposing team's feet. The trap hurts Pokémon that switch into battle."),
("zap cannon",13,120,5,0,50,10,3,"The user fires an electric blast like a cannon to inflict damage and cause paralysis."),
("foresight",1,0,40,0,0,10,1,"Enables a Ghost-type target to be hit by Normal- and Fighting-type attacks. It also enables an evasive target to be hit."),
("destiny bond",8,0,5,0,0,7,1,"When this move is used, if the user faints, the Pokémon that landed the knockout hit also faints."),
("perish song",1,0,5,0,0,12,1,"Any Pokémon that hears this song faints in three turns, unless it switches out of battle."),
("icy wind",15,55,15,0,95,11,3,"The user attacks with a gust of chilled air. It also reduces the targets' Speed stat."),
("detect",2,0,5,4,0,7,1,"It enables the user to evade all attacks. Its chance of failing rises if it is used in succession."),
("bone rush",5,25,10,0,90,10,2,"The user strikes the target with a hard bone two to five times in a row."),
("lock on",1,0,5,0,0,10,1,"The user takes sure aim at the target. It ensures the next attack does not fail to hit the target."),
("outrage",16,120,10,0,100,8,2,"The user rampages and attacks for two to three turns. It then becomes confused, however."),
("sandstorm",6,0,10,0,0,12,1,"A five-turn sandstorm is summoned to hurt all combatants except the Rock, Ground, and Steel types."),
("giga drain",12,75,10,0,100,10,3,"A nutrient-draining attack. The user's HP is restored by half the damage taken by the target."),
("endure",1,0,10,4,0,7,1,"The user endures any attack with at least 1 HP. Its chance of failing rises if it is used in succession."),
("charm",1,0,20,0,100,10,1,"The user gazes at the target rather charmingly, making it less wary. The target's Attack is harshly lowered."),
("rollout",6,30,20,0,90,10,2,"The user continually rolls into the target over five turns. It becomes stronger each time it hits."),
("false swipe",1,40,40,0,100,10,2,"A restrained attack that prevents the target from fainting. The target is left with at least 1 HP."),
("swagger",1,0,15,0,90,10,1,"The user enrages and confuses the target. However, it also sharply raises the target's Attack stat."),
("milk drink",1,0,10,0,0,7,1,"The user restores its own HP by up to half of its maximum HP. May also be used in the field to heal HP."),
("spark",13,65,20,0,100,10,2,"The user throws an electrically charged tackle at the target. It may also leave the target with paralysis."),
("fury cutter",7,20,20,0,95,10,2,"The target is slashed with scythes or claws. Its power increases if it hits in succession."),
("steel wing",9,70,25,0,90,10,2,"The target is hit with wings of steel. It may also raise the user's Defense stat."),
("mean look",1,0,5,0,0,10,1,"The user pins the target with a dark, arresting look. The target becomes unable to flee."),
("attract",1,0,15,0,100,10,1,"If it is the opposite gender of the user, the target becomes infatuated and less likely to attack."),
("sleep talk",1,0,10,0,0,7,1,"While it is asleep, the user randomly uses one of the moves it knows."),
("heal bell",1,0,5,0,0,4,1,"The user makes a soothing bell chime to heal the status problems of all the party Pokémon."),
("return",1,1,20,0,100,10,2,"A full-power attack that grows more powerful the more the user likes its Trainer."),
("present",1,1,15,0,90,10,2,"The user attacks by giving the target a gift with a hidden trap. It restores HP sometimes, however."),
("frustration",1,1,20,0,100,10,2,"A full-power attack that grows more powerful the less the user likes its Trainer."),
("safeguard",1,0,25,0,0,4,1,"The user creates a protective field that prevents status problems for five turns."),
("pain split",1,0,20,0,0,10,1,"The user adds its HP to the target's HP, then equally shares the combined HP with the target."),
("sacred fire",10,100,5,0,95,10,2,"The target is razed with a mystical fire of great intensity. It may also leave the target with a burn."),
("magnitude",5,1,30,0,100,9,2,"The user looses a ground-shaking quake affecting everyone around the user. Its power varies."),
("dynamicpunch",2,100,5,0,50,10,2,"The user punches the target with full, concentrated power. It confuses the target if it hits."),
("megahorn",7,120,10,0,85,10,2,"Using its tough and impressive horn, the user rams into the target with no letup."),
("dragonbreath",16,60,20,0,100,10,3,"The user exhales a mighty gust that inflicts damage. It may also leave the target with paralysis."),
("baton pass",1,0,40,0,0,7,1,"The user switches places with a party Pokémon in waiting, passing along any stat changes."),
("encore",1,0,5,0,100,10,1,"The user compels the target to keep using only the move it last used for three turns."),
("pursuit",17,40,20,0,100,10,2,"An attack move that inflicts double damage if used on a target that is switching out of battle."),
("rapid spin",1,20,40,0,100,10,2,"A spin attack that can also eliminate such moves as Bind, Wrap, Leech Seed, and Spikes."),
("sweet scent",1,0,20,0,100,11,1,"A sweet scent that lowers the opposing team's evasiveness. It also lures wild Pokémon if used in grass, etc."),
("iron tail",9,100,15,0,75,10,2,"The target is slammed with a steel-hard tail. It may also lower the target's Defense stat."),
("metal claw",9,50,35,0,95,10,2,"The target is raked with steel claws. It may also raise the user's Attack stat."),
("vital throw",2,70,10,-1,0,10,2,"The user attacks last. In return, this throw move is guaranteed not to miss."),
("morning sun",1,0,5,0,0,7,1,"The user restores its own HP. The amount of HP regained varies with the weather."),
("synthesis",12,0,5,0,0,7,1,"The user restores its own HP. The amount of HP regained varies with the weather."),
("moonlight",1,0,5,0,0,7,1,"The user restores its own HP. The amount of HP regained varies with the weather."),
("hidden power",1,1,15,0,100,10,3,"A unique attack that varies in type and intensity depending on the Pokémon using it."),
("cross chop",2,100,5,0,80,10,2,"The user delivers a double chop with its forearms crossed. Critical hits land more easily."),
("twister",16,40,20,0,100,11,3,"The user whips up a vicious tornado to tear at the opposing team. It may also make targets flinch."),
("rain dance",11,0,5,0,0,12,1,"The user summons a heavy rain that falls for five turns, powering up Water-type moves."),
("sunny day",10,0,5,0,0,12,1,"The user intensifies the sun for five turns, powering up Fire-type moves."),
("crunch",17,80,15,0,100,10,2,"The user crunches up the target with sharp fangs. It may also lower the target's Defense stat."),
("mirror coat",14,1,20,-5,100,1,3,"A retaliation move that counters any special attack, inflicting double the damage taken."),
("psych up",1,0,10,0,0,10,1,"The user hypnotizes itself into copying any stat change made by the target."),
("extremespeed",1,80,5,2,100,10,2,"The user charges the target at blinding speed. This attack always goes before any other move."),
("ancientpower",6,60,5,0,100,10,3,"The user attacks with a prehistoric power. It may also raise all the user's stats at once."),
("shadow ball",8,80,15,0,100,10,3,"The user hurls a shadowy blob at the target. It may also lower the target's Sp. Def stat."),
("future sight",14,100,10,0,100,10,3,"Two turns after this move is used, a hunk of psychic energy attacks the target."),
("rock smash",2,40,15,0,100,10,2,"The user attacks with a punch that can shatter a rock. It may also lower the target's Defense stat."),
("whirlpool",11,35,15,0,85,10,3,"Traps foes in a violent swirling whirlpool for four to five turns."),
("beat up",17,1,10,0,100,10,2,"The user gets all party Pokémon to attack the target. The more party Pokémon, the greater the number of attacks."),
("fake out",1,40,10,3,100,10,2,"An attack that hits first and makes the target flinch. It only works the first turn the user is in battle."),
("uproar",1,90,10,0,100,8,3,"The user attacks in an uproar for three turns. Over that time, no one can fall asleep."),
("stockpile",1,0,20,0,0,7,1,"The user charges up power and raises both its Defense and Sp. Def. The move can be used three times."),
("spit up",1,1,10,0,100,10,3,"The power stored using the move Stockpile is released at once in an attack. The more power is stored, the greater the damage."),
("swallow",1,0,10,0,0,7,1,"The power stored using the move Stockpile is absorbed by the user to heal its HP. Storing more power heals more HP."),
("heat wave",10,100,10,0,90,11,3,"The user attacks by exhaling hot breath on the opposing team. It may also leave targets with a burn."),
("hail",15,0,10,0,0,12,1,"The user summons a hailstorm lasting five turns. It damages all Pokémon except the Ice type."),
("torment",17,0,15,0,100,10,1,"The user torments and enrages the target, making it incapable of using the same move twice in a row."),
("flatter",17,0,15,0,100,10,1,"Flattery is used to confuse the target. However, it also raises the target's Sp. Atk stat."),
("will o wisp",10,0,15,0,75,10,1,"The user shoots a sinister, bluish-white flame at the target to inflict a burn."),
("memento",17,0,10,0,100,10,1,"The user faints when using this move. In return, it harshly lowers the target's Attack and Sp. Atk."),
("facade",1,70,20,0,100,10,2,"An attack move that doubles its power if the user is poisoned, burned, or has paralysis."),
("focus punch",2,150,20,-3,100,10,2,"The user focuses its mind before launching a punch. It will fail if the user is hit before it is used."),
("smellingsalt",1,60,10,0,100,10,2,"This attack inflicts double damage on a target with paralysis. It also cures the target's paralysis, however."),
("follow me",1,0,20,3,0,7,1,"The user draws attention to itself, making all targets take aim only at the user."),
("nature power",1,0,20,0,0,1,1,"An attack that makes use of nature's power. Its effects vary depending on the user's environment."),
("charge",13,0,20,0,0,7,1,"The user boosts the power of the Electric move it uses on the next turn. It also raises the user's Sp. Def stat."),
("taunt",17,0,20,0,100,10,1,"The target is taunted into a rage that allows it to use only attack moves for three turns."),
("helping hand",1,0,20,5,0,3,1,"The user assists an ally by boosting the power of its attack."),
("trick",14,0,10,0,100,10,1,"The user catches the target off guard and swaps its held item with its own."),
("role play",14,0,10,0,0,10,1,"The user mimics the target completely, copying the target's natural Ability."),
("wish",1,0,10,0,0,7,1,"One turn after this move is used, the target's HP is restored by half the user's maximum HP."),
("assist",1,0,20,0,0,7,1,"The user hurriedly and randomly uses a move among those known by other Pokémon in the party."),
("ingrain",12,0,20,0,0,7,1,"The user lays roots that restore its HP on every turn. Because it is rooted, it can't switch out."),
("superpower",2,120,5,0,100,10,2,"The user attacks the target with great power. However, it also lowers the user's Attack and Defense."),
("magic coat",14,0,15,4,0,7,1,"A barrier reflects back to the target moves like Leech Seed and moves that damage status."),
("recycle",1,0,10,0,0,7,1,"The user recycles a held item that has been used in battle so it can be used again."),
("revenge",2,60,10,-4,100,10,2,"An attack move that inflicts double the damage if the user has been hurt by the opponent in the same turn."),
("brick break",2,75,15,0,100,10,2,"The user attacks with a swift chop. It can also break any barrier such as Light Screen and Reflect."),
("yawn",1,0,10,0,0,10,1,"The user lets loose a huge yawn that lulls the target into falling asleep on the next turn."),
("knock off",17,20,20,0,100,10,2,"The user slaps down the target's held item, preventing that item from being used in the battle."),
("endeavor",1,1,5,0,100,10,2,"An attack move that cuts down the target's HP to equal the user's HP."),
("eruption",10,150,5,0,100,11,3,"The user attacks the opposing team with explosive fury. The lower the user's HP, the less powerful this attack becomes."),
("skill swap",14,0,10,0,0,10,1,"The user employs its psychic power to exchange Abilities with the target."),
("imprison",14,0,10,0,0,7,1,"If the opponents know any move also known by the user, the opponents are prevented from using it."),
("refresh",1,0,20,0,0,7,1,"The user rests to cure itself of a poisoning, burn, or paralysis."),
("grudge",8,0,5,0,0,7,1,"If the user faints, the user's grudge fully depletes the PP of the opponent's move that knocked it out."),
("snatch",17,0,10,4,0,7,1,"The user steals the effects of any healing or stat-changing move the opponent attempts to use."),
("secret power",1,70,20,0,100,10,2,"The user attacks the target with a secret power. Its added effects vary depending on the user's environment."),
("dive",11,80,10,0,100,10,2,"Diving on the first turn, the user floats up and attacks on the second turn. It can be used to dive deep in the ocean."),
("arm thrust",2,15,20,0,100,10,2,"The user looses a flurry of open-palmed arm thrusts that hit two to five times in a row."),
("camouflage",1,0,20,0,0,7,1,"The user's type is changed depending on its environment, such as at water's edge, in grass, or in a cave."),
("tail glow",7,0,20,0,0,7,1,"The user stares at flashing lights to focus its mind, drastically raising its Sp. Atk stat."),
("luster purge",14,70,5,0,100,10,3,"The user lets loose a damaging burst of light. It may also reduce the target's Sp. Def stat."),
("mist ball",14,70,5,0,100,10,3,"A mistlike flurry of down envelops and damages the target. It may also lower the target's Sp. Atk."),
("featherdance",3,0,15,0,100,10,1,"The user covers the target's body with a mass of down that harshly lowers its Attack stat."),
("teeter dance",1,0,20,0,100,9,1,"The user performs a wobbly dance that confuses the Pokémon around it."),
("blaze kick",10,85,10,0,90,10,2,"The user launches a kick that lands a critical hit more easily. It may also leave the target with a burn."),
("mud sport",5,0,15,0,0,12,1,"The user covers itself with mud. It weakens Electric-type moves while the user is in the battle."),
("ice ball",15,30,20,0,90,10,2,"The user continually rolls into the target over five turns. It becomes stronger each time it hits."),
("needle arm",12,60,15,0,100,10,2,"The user attacks by wildly swinging its thorny arms. It may also make the target flinch."),
("slack off",1,0,10,0,0,7,1,"The user slacks off, restoring its own HP by up to half of its maximum HP."),
("hyper voice",1,90,10,0,100,11,3,"The user lets loose a horribly echoing shout with the power to inflict damage."),
("poison fang",4,50,15,0,100,10,2,"The user bites the target with toxic fangs. It may also leave the target badly poisoned."),
("crush claw",1,75,10,0,95,10,2,"The user slashes the target with hard and sharp claws. It may also lower the target's Defense."),
("blast burn",10,150,5,0,90,10,3,"The target is razed by a fiery explosion. The user must rest on the next turn, however."),
("hydro cannon",11,150,5,0,90,10,3,"The target is hit with a watery blast. The user must rest on the next turn, however."),
("meteor mash",9,100,10,0,85,10,2,"The target is hit with a hard punch fired like a meteor. It may also raise the user's Attack."),
("astonish",8,30,15,0,100,10,2,"The user attacks the target while shouting in a startling fashion. It may also make the target flinch."),
("weather ball",1,50,10,0,100,10,3,"An attack move that varies in power and type depending on the weather."),
("aromatherapy",12,0,5,0,0,4,1,"The user releases a soothing scent that heals all status problems affecting the user's party."),
("fake tears",17,0,20,0,100,10,1,"The user feigns crying to fluster the target, harshly lowering its Sp. Def stat."),
("air cutter",3,55,25,0,95,11,3,"The user launches razor-like wind to slash the opposing team. Critical hits land more easily."),
("overheat",10,140,5,0,90,10,3,"The user attacks the target at full power. The attack's recoil harshly reduces the user's Sp. Atk stat."),
("odor sleuth",1,0,40,0,0,10,1,"Enables a Ghost-type target to be hit with Normal- and Fighting-type attacks. It also enables an evasive target to be hit."),
("rock tomb",6,50,10,0,80,10,2,"Boulders are hurled at the target. It also lowers the target's Speed by preventing its movement."),
("silver wind",7,60,5,0,100,10,3,"The target is attacked with powdery scales blown by wind. It may also raise all the user's stats."),
("metal sound",9,0,40,0,85,10,1,"A horrible sound like scraping metal harshly reduces the target's Sp. Def stat."),
("grasswhistle",12,0,15,0,55,10,1,"The user plays a pleasant melody that lulls the target into a deep sleep."),
("tickle",1,0,20,0,100,10,1,"The user tickles the target into laughing, reducing its Attack and Defense stats."),
("cosmic power",14,0,20,0,0,7,1,"The user absorbs a mystical power from space to raise its Defense and Sp. Def stats."),
("water spout",11,150,5,0,100,11,3,"The user spouts water to damage the opposing team. The lower the user's HP, the less powerful it becomes."),
("signal beam",7,75,15,0,100,10,3,"The user attacks with a sinister beam of light. It may also confuse the target."),
("shadow punch",8,60,20,0,0,10,2,"The user throws a punch from the shadows. The punch lands without fail."),
("extrasensory",14,80,30,0,100,10,3,"The user attacks with an odd, unseeable power. It may also make the target flinch."),
("sky uppercut",2,85,15,0,90,10,2,"The user attacks the target with an uppercut thrown skyward with force."),
("sand tomb",5,35,15,0,85,10,2,"The user traps the target inside a harshly raging sandstorm for four to five turns."),
("sheer cold",15,1,5,0,30,10,3,"The target is attacked with a blast of absolute-zero cold. The target instantly faints if it hits."),
("muddy water",11,95,10,0,85,11,3,"The user attacks by shooting muddy water at the opposing team. It may also lower the targets' accuracy."),
("bullet seed",12,25,30,0,100,10,2,"The user forcefully shoots seeds at the target. Two to five seeds are shot in rapid succession."),
("aerial ace",3,60,20,0,0,10,2,"The user confounds the target with speed, then slashes. The attack lands without fail."),
("icicle spear",15,25,30,0,100,10,2,"The user launches sharp icicles at the target. It strikes two to five times in a row."),
("iron defense",9,0,15,0,0,7,1,"The user hardens its body's surface like iron, sharply raising its Defense stat."),
("block",1,0,5,0,0,10,1,"The user blocks the target's way with arms spread wide to prevent escape."),
("howl",1,0,40,0,0,7,1,"The user howls loudly to raise its spirit, boosting its Attack stat."),
("dragon claw",16,80,15,0,100,10,2,"The user slashes the target with huge, sharp claws."),
("frenzy plant",12,150,5,0,90,10,3,"The user slams the target with an enormous tree. The user can't move on the next turn."),
("bulk up",2,0,20,0,0,7,1,"The user tenses its muscles to bulk up its body, boosting both its Attack and Defense stats."),
("bounce",3,85,5,0,85,10,2,"The user bounces up high, then drops on the target on the second turn. It may also leave the target with paralysis."),
("mud shot",5,55,15,0,95,10,3,"The user attacks by hurling a blob of mud at the target. It also reduces the target's Speed."),
("poison tail",4,50,25,0,100,10,2,"The user hits the target with its tail. It may also poison the target. Critical hits land more easily."),
("covet",1,60,40,0,100,10,2,"The user endearingly approaches the target, then steals the target's held item."),
("volt tackle",13,120,15,0,100,10,2,"The user electrifies itself, then charges. It causes considerable damage to the user and may leave the target with paralysis."),
("magical leaf",12,60,20,0,0,10,3,"The user scatters curious leaves that chase the target. This attack will not miss."),
("water sport",11,0,15,0,0,12,1,"The user soaks itself with water. The move weakens Fire-type moves while the user is in the battle."),
("calm mind",14,0,20,0,0,7,1,"The user quietly focuses its mind and calms its spirit to raise its Sp. Atk and Sp. Def stats."),
("leaf blade",12,90,15,0,100,10,2,"The user handles a sharp leaf like a sword and attacks by cutting its target. Critical hits land more easily."),
("dragon dance",16,0,20,0,0,7,1,"The user vigorously performs a mystic, powerful dance that boosts its Attack and Speed stats."),
("rock blast",6,25,10,0,90,10,2,"The user hurls hard rocks at the target. Two to five rocks are launched in quick succession."),
("shock wave",13,60,20,0,0,10,3,"The user strikes the target with a quick jolt of electricity. This attack cannot be evaded."),
("water pulse",11,60,20,0,100,10,3,"The user attacks the target with a pulsing blast of water. It may also confuse the target."),
("doom desire",9,140,5,0,100,10,3,"Two turns after this move is used, the user blasts the target with a concentrated bundle of light."),
("psycho boost",14,140,5,0,90,10,3,"The user attacks the target at full power. The attack's recoil harshly reduces the user's Sp. Atk stat."),
("roost",3,0,10,0,0,7,1,"The user lands and rests its body. It restores the user's HP by up to half of its max HP."),
("gravity",14,0,5,0,0,12,1,"Gravity is intensified for five turns, making moves involving flying unusable and negating Levitate."),
("miracle eye",14,0,40,0,0,10,1,"Enables a Dark-type target to be hit by Psychic-type attacks. It also enables an evasive target to be hit."),
("wake up slap",2,60,10,0,100,10,2,"This attack inflicts big damage on a sleeping target. It also wakes the target up, however."),
("hammer arm",2,100,10,0,90,10,2,"The user swings and hits with its strong and heavy fist. It lowers the user's Speed, however."),
("gyro ball",9,1,5,0,100,10,2,"The user tackles the target with a high-speed spin. The slower the user, the greater the damage."),
("healing wish",14,0,10,0,0,7,1,"The user faints. In return, the Pokémon taking its place will have its HP restored and status cured."),
("brine",11,65,10,0,100,10,3,"If the target's HP is down to about half, this attack will hit with double the power."),
("natural gift",1,1,15,0,100,10,2,"The user draws power to attack by using its held Berry. The Berry determines its type and power."),
("feint",1,30,10,2,100,10,2,"An attack that hits a target using Protect or Detect. It also lifts the effects of those moves."),
("pluck",3,60,20,0,100,10,2,"The user pecks the target. If the target is holding a Berry, the user eats it and gains its effect."),
("tailwind",3,0,30,0,0,4,1,"The user whips up a turbulent whirlwind that ups the Speed of all party Pokémon for four turns."),
("acupressure",1,0,30,0,0,5,1,"The user applies pressure to stress points, sharply boosting one of its stats."),
("metal burst",9,1,10,0,100,1,2,"The user retaliates with much greater power against the target that last inflicted damage on it."),
("u turn",7,70,20,0,100,10,2,"After making its attack, the user rushes back to switch places with a party Pokémon in waiting."),
("close combat",2,120,5,0,100,10,2,"The user fights the target up close without guarding itself. It also cuts the user's Defense and Sp. Def."),
("payback",17,50,10,0,100,10,2,"If the user moves after the target, this attack's power will be doubled."),
("assurance",17,50,10,0,100,10,2,"If the target has already taken some damage in the same turn, this attack's power is doubled."),
("embargo",17,0,15,0,100,10,1,"It prevents the target from using its held item. Its Trainer is also prevented from using items on it."),
("fling",17,1,10,0,100,10,2,"The user flings its held item at the target to attack. Its power and effects depend on the item."),
("psycho shift",14,0,10,0,90,10,1,"Using its psychic power of suggestion, the user transfers its status problems to the target."),
("trump card",1,1,5,0,0,10,3,"The fewer PP this move has, the greater its attack power."),
("heal block",14,0,15,0,100,11,1,"For five turns, the user prevents the opposing team from using any moves, Abilities, or held items that recover HP."),
("wring out",1,1,5,0,100,10,3,"The user powerfully wrings the target. The more HP the target has, the greater this attack's power."),
("power trick",14,0,10,0,0,7,1,"The user employs its psychic power to switch its Attack with its Defense stat."),
("gastro acid",4,0,10,0,100,10,1,"The user hurls up its stomach acids on the target. The fluid eliminates the effect of the target's Ability."),
("lucky chant",1,0,30,0,0,4,1,"The user chants an incantation toward the sky, preventing opposing Pokémon from landing critical hits."),
("me first",1,1,20,0,0,2,1,"The user tries to cut ahead of the target to steal and use the target's intended move with greater power."),
("copycat",1,0,20,0,0,7,1,"The user mimics the move used immediately before it. The move fails if no other move has been used yet."),
("power swap",14,0,10,0,0,10,1,"The user employs its psychic power to switch changes to its Attack and Sp. Atk with the target."),
("guard swap",14,0,10,0,0,10,1,"The user employs its psychic power to switch changes to its Defense and Sp. Def with the target."),
("punishment",17,1,5,0,100,10,2,"This attack's power increases the more the target has powered up with stat changes."),
("last resort",1,140,5,0,100,10,2,"This move can be used only after the user has used all the other moves it knows in the battle."),
("worry seed",12,0,10,0,100,10,1,"A seed that causes worry is planted on the target. It prevents sleep by making its Ability Insomnia."),
("sucker punch",17,80,5,1,100,10,2,"This move enables the user to attack first. It fails if the target is not readying an attack, however."),
("toxic spikes",4,0,20,0,0,6,1,"The user lays a trap of poison spikes at the opponent's feet. They poison opponents that switch into battle."),
("heart swap",14,0,10,0,0,10,1,"The user employs its psychic power to switch stat changes with the target."),
("aqua ring",11,0,20,0,0,7,1,"The user envelops itself in a veil made of water. It regains some HP on every turn."),
("magnet rise",13,0,10,0,0,7,1,"The user levitates using electrically generated magnetism for five turns."),
("flare blitz",10,120,15,0,100,10,2,"The user cloaks itself in fire and charges at the target. The user sustains serious damage and may leave the target burned."),
("force palm",2,60,10,0,100,10,2,"The target is attacked with a shock wave. It may also leave the target with paralysis."),
("aura sphere",2,90,20,0,0,10,3,"The user looses a blast of aura power from deep within its body at the target. This move is certain to hit."),
("rock polish",6,0,20,0,0,7,1,"The user polishes its body to reduce drag. It can sharply raise the Speed stat."),
("poison jab",4,80,20,0,100,10,2,"The target is stabbed with a tentacle or arm steeped in poison. It may also poison the target."),
("dark pulse",17,80,15,0,100,10,3,"The user releases a horrible aura imbued with dark thoughts. It may also make the target flinch."),
("night slash",17,70,15,0,100,10,2,"The user slashes the target the instant an opportunity arises. Critical hits land more easily."),
("aqua tail",11,90,10,0,90,10,2,"The user attacks by swinging its tail as if it were a vicious wave in a raging storm."),
("seed bomb",12,80,15,0,100,10,2,"The user slams a barrage of hard-shelled seeds down on the target from above."),
("air slash",3,75,20,0,95,10,3,"The user attacks with a blade of air that slices even the sky. It may also make the target flinch."),
("x scissor",7,80,15,0,100,10,2,"The user slashes at the target by crossing its scythes or claws as if they were a pair of scissors."),
("bug buzz",7,90,10,0,100,10,3,"The user vibrates its wings to generate a damaging sound wave. It may also lower the target's Sp. Def stat."),
("dragon pulse",16,90,10,0,100,10,3,"The target is attacked with a shock wave generated by the user's gaping mouth."),
("dragon rush",16,100,10,0,75,10,2,"The user tackles the target while exhibiting overwhelming menace. It may also make the target flinch."),
("power gem",6,70,20,0,100,10,3,"The user attacks with a ray of light that sparkles as if it were made of gemstones."),
("drain punch",2,75,10,0,100,10,2,"An energy-draining punch. The user's HP is restored by half the damage taken by the target."),
("vacuum wave",2,40,30,1,100,10,3,"The user whirls its fists to send a wave of pure vacuum at the target. This move always goes first."),
("focus blast",2,120,5,0,70,10,3,"The user heightens its mental focus and unleashes its power. It may also lower the target's Sp. Def."),
("energy ball",12,80,10,0,100,10,3,"The user draws power from nature and fires it at the target. It may also lower the target's Sp. Def."),
("brave bird",3,120,15,0,100,10,2,"The user tucks in its wings and charges from a low altitude. The user also takes serious damage."),
("earth power",5,90,10,0,100,10,3,"The user makes the ground under the target erupt with power. It may also lower the target's Sp. Def."),
("switcheroo",17,0,10,0,100,10,1,"The user trades held items with the target faster than the eye can follow."),
("giga impact",1,150,5,0,90,10,2,"The user charges at the target using every bit of its power. The user must rest on the next turn."),
("nasty plot",17,0,20,0,0,7,1,"The user stimulates its brain by thinking bad thoughts. It sharply raises the user's Sp. Atk."),
("bullet punch",9,40,30,1,100,10,2,"The user strikes the target with tough punches as fast as bullets. This move always goes first."),
("avalanche",15,60,10,-4,100,10,2,"An attack move that inflicts double the damage if the user has been hurt by the target in the same turn."),
("ice shard",15,40,30,1,100,10,2,"The user flash freezes chunks of ice and hurls them at the target. This move always goes first."),
("shadow claw",8,70,15,0,100,10,2,"The user slashes with a sharp claw made from shadows. Critical hits land more easily."),
("thunder fang",13,65,15,0,95,10,2,"The user bites with electrified fangs. It may also make the target flinch or leave it with paralysis."),
("ice fang",15,65,15,0,95,10,2,"The user bites with cold-infused fangs. It may also make the target flinch or leave it frozen."),
("fire fang",10,65,15,0,95,10,2,"The user bites with flame-cloaked fangs. It may also make the target flinch or leave it burned."),
("shadow sneak",8,40,30,1,100,10,2,"The user extends its shadow and attacks the target from behind. This move always goes first."),
("mud bomb",5,65,10,0,85,10,3,"The user launches a hard-packed mud ball to attack. It may also lower the target's accuracy."),
("psycho cut",14,70,20,0,100,10,2,"The user tears at the target with blades formed by psychic power. Critical hits land more easily."),
("zen headbutt",14,80,15,0,90,10,2,"The user focuses its willpower to its head and attacks the target. It may also make the target flinch."),
("mirror shot",9,65,10,0,85,10,3,"The user looses a flash of energy at the target from its polished body. It may also lower the target's accuracy."),
("flash cannon",9,80,10,0,100,10,3,"The user gathers all its light energy and releases it at once. It may also lower the target's Sp. Def stat."),
("rock climb",1,90,20,0,85,10,2,"The user attacks the target by smashing into it with incredible force. It may also confuse the target."),
("defog",3,0,15,0,0,10,1,"A strong wind blows away the target's obstacles such as Reflect or Light Screen. It also lowers the target's evasiveness."),
("trick room",14,0,5,-7,0,12,1,"The user creates a bizarre area in which slower Pokémon get to move first for five turns."),
("draco meteor",16,140,5,0,90,10,3,"Comets are summoned down from the sky onto the target. The attack's recoil harshly reduces the user's Sp. Atk stat."),
("discharge",13,80,15,0,100,9,3,"A flare of electricity is loosed to strike the area around the user. It may also cause paralysis."),
("lava plume",10,80,15,0,100,9,3,"An inferno of scarlet flames torches everything around the user. It may leave targets with a burn."),
("leaf storm",12,140,5,0,90,10,3,"The user whips up a storm of leaves around the target. The attack's recoil harshly reduces the user's Sp. Atk stat."),
("power whip",12,120,10,0,85,10,2,"The user violently whirls its vines or tentacles to harshly lash the target."),
("rock wrecker",6,150,5,0,90,10,2,"The user launches a huge boulder at the target to attack. It must rest on the next turn, however."),
("cross poison",4,70,20,0,100,10,2,"A slashing attack with a poisonous blade that may also leave the target poisoned. Critical hits land more easily."),
("gunk shot",4,120,5,0,70,10,2,"The user shoots filthy garbage at the target to attack. It may also poison the target."),
("iron head",9,80,15,0,100,10,2,"The user slams the target with its steel-hard head. It may also make the target flinch."),
("magnet bomb",9,60,20,0,0,10,2,"The user launches steel bombs that stick to the target. This attack will not miss."),
("stone edge",6,100,5,0,80,10,2,"The user stabs the foe with sharpened stones from below. It has a high critical-hit ratio."),
("captivate",1,0,20,0,100,11,1,"If it is the opposite gender of the user, the target is charmed into harshly lowering its Sp. Atk stat."),
("stealth rock",6,0,20,0,0,6,1,"The user lays a trap of levitating stones around the opponent's team. The trap hurts opponents that switch into battle."),
("grass knot",12,1,20,0,100,10,3,"The user snares the target with grass and trips it. The heavier the target, the greater the damage."),
("chatter",3,60,20,0,100,10,3,"The user attacks using a sound wave based on words it has learned. It may also confuse the target."),
("judgment",1,100,10,0,100,10,3,"The user releases countless shots of light at the target. Its type varies with the kind of Plate the user is holding."),
("bug bite",7,60,20,0,100,10,2,"The user bites the target. If the target is holding a Berry, the user eats it and gains its effect."),
("charge beam",13,50,10,0,90,10,3,"The user attacks with an electric charge. The user may use any remaining electricity to raise its Sp. Atk stat."),
("wood hammer",12,120,15,0,100,10,2,"The user slams its rugged body into the target to attack. The user also sustains serious damage."),
("aqua jet",11,40,20,1,100,10,2,"The user lunges at the target at a speed that makes it almost invisible. It is sure to strike first."),
("attack order",7,90,15,0,100,10,2,"The user calls out its underlings to pummel the target. Critical hits land more easily."),
("defend order",7,0,10,0,0,7,1,"The user calls out its underlings to shield its body, raising its Defense and Sp. Def stats."),
("heal order",7,0,10,0,0,7,1,"The user calls out its underlings to heal it. The user regains up to half of its max HP."),
("head smash",6,150,5,0,80,10,2,"The user attacks the target with a hazardous, full-power headbutt. The user also takes terrible damage."),
("double hit",1,35,10,0,90,10,2,"The user slams the target with a long tail, vines, or tentacle. The target is hit twice in a row."),
("roar of time",16,150,5,0,90,10,3,"The user blasts the target with power that distorts even time. The user must rest on the next turn."),
("spacial rend",16,100,5,0,95,10,3,"The user tears the target along with the space around it. Critical hits land more easily."),
("lunar dance",14,0,10,0,0,7,1,"The user faints. In return, the Pokémon taking its place will have its status and HP fully restored."),
("crush grip",1,1,5,0,100,10,2,"The target is crushed with great force. The attack is more powerful the more HP the target has left."),
("magma storm",10,120,5,0,75,10,3,"The target becomes trapped within a maelstrom of fire that rages for four to five turns."),
("dark void",17,0,10,0,80,11,1,"Opposing Pokémon are dragged into a world of total darkness that makes them sleep."),
("seed flare",12,120,5,0,85,10,3,"The user emits a shock wave from its body to attack its target. It may harshly lower the target's Sp. Def."),
("ominous wind",8,60,5,0,100,10,3,"The user blasts the target with a gust of repulsive wind. It may also raise all the user's stats at once."),
("shadow force",8,120,5,0,100,10,2,"The user disappears, then strikes the target on the second turn. It hits even if the target protects itself."),
("hone claws",17,0,15,0,0,7,1,"The user sharpens its claws to boost its Attack stat and accuracy."),
("wide guard",6,0,10,3,0,4,1,"The user and its allies are protected from wide-ranging attacks for one turn. If used in succession, its chance of failing rises."),
("guard split",14,0,10,0,0,10,1,"The user employs its psychic power to average its Defense and Sp. Def stats with those of its target's."),
("power split",14,0,10,0,0,10,1,"The user employs its psychic power to average its Attack and Sp. Atk stats with those of the target's."),
("wonder room",14,0,10,-7,0,12,1,"The user creates a bizarre area in which Pokémon's Defense and Sp. Def stats are swapped for five turns."),
("psyshock",14,80,10,0,100,10,3,"The user materializes an odd psychic wave to attack the target. This attack does physical damage."),
("venoshock",4,65,10,0,100,10,3,"The user drenches the target in a special poisonous liquid. Its power is doubled if the target is poisoned."),
("autotomize",9,0,15,0,0,7,1,"The user sheds part of its body to make itself lighter and sharply raise its Speed stat."),
("rage powder",7,0,20,3,0,7,1,"The user scatters a cloud of irritating powder to draw attention to itself. Opponents aim only at the user."),
("telekinesis",14,0,15,0,0,10,1,"The user makes the target float with its psychic power. The target is easier to hit for three turns."),
("magic room",14,0,10,-7,0,12,1,"The user creates a bizarre area in which Pokémon's held items lose their effects for five turns."),
("smack down",6,50,15,0,100,10,2,"The user throws a stone or projectile to attack an opponent. A flying Pokémon will fall to the ground when hit."),
("storm throw",2,40,10,0,100,10,2,"The user strikes the target with a fierce blow. This attack always results in a critical hit."),
("flame burst",10,70,15,0,100,10,3,"The user attacks the target with a bursting flame. The bursting flame damages Pokémon next to the target as well."),
("sludge wave",4,95,10,0,100,9,3,"It swamps the area around the user with a giant sludge wave. It may also poison those hit."),
("quiver dance",7,0,20,0,0,7,1,"The user lightly performs a beautiful, mystic dance. It boosts the user's Sp. Atk, Sp. Def, and Speed stats."),
("heavy slam",9,1,10,0,100,10,2,"The user slams into the target with its heavy body. The more the user outweighs the target, the greater its damage."),
("synchronoise",14,70,15,0,100,9,3,"Using an odd shock wave, the user inflicts damage on any Pokémon of the same type in the area around it."),
("electro ball",13,1,10,0,100,10,3,"The user hurls an electric orb at the target. The faster the user is than the target, the greater the damage."),
("soak",11,0,20,0,100,10,1,"The user shoots a torrent of water at the target and changes the target's type to Water."),
("flame charge",10,50,20,0,100,10,2,"The user cloaks itself with flame and attacks. Building up more power, it raises the user's Speed stat."),
("coil",4,0,20,0,0,7,1,"The user coils up and concentrates. This raises its Attack and Defense stats as well as its accuracy."),
("low sweep",2,60,20,0,100,10,2,"The user attacks the target's legs swiftly, reducing the target's Speed stat."),
("acid spray",4,40,20,0,100,10,3,"The user spits fluid that works to melt the target. This harshly reduces the target's Sp. Def stat."),
("foul play",17,95,15,0,100,10,2,"The user turns the target's power against it. The higher the target's Attack stat, the greater the damage."),
("simple beam",1,0,15,0,100,10,1,"The user's mysterious psychic wave changes the target's Ability to Simple."),
("entrainment",1,0,15,0,100,10,1,"The user dances with an odd rhythm that compels the target to mimic it, making the target's Ability the same as the user's."),
("after you",1,0,15,0,0,10,1,"The user helps the target and makes it use its move right after the user."),
("round",1,60,15,0,100,10,3,"The user attacks the target with a song. Others can join in the Round and make the attack do greater damage."),
("echoed voice",1,40,15,0,100,10,3,"The user attacks the target with an echoing voice. If this move is used every turn, it does greater damage."),
("chip away",1,70,20,0,100,10,2,"Looking for an opening, the user strikes continually. The target's stat changes don't affect this attack's damage."),
("clear smog",4,50,15,0,0,10,3,"The user attacks by throwing a clump of special mud. All status changes are returned to normal."),
("stored power",14,20,10,0,100,10,3,"The user attacks the target with stored power. The more the user's stats are raised, the greater the damage."),
("quick guard",2,0,15,3,0,4,1,"The user protects itself and its allies from priority moves. If used in succession, its chance of failing rises."),
("ally switch",14,0,15,1,0,7,1,"The user teleports using a strange power and switches its place with one of its allies."),
("scald",11,80,15,0,100,10,3,"The user shoots boiling hot water at its target. It may also leave the target with a burn."),
("shell smash",1,0,15,0,0,7,1,"The user breaks its shell, lowering its Defense and Sp. Def stats but sharply raising Attack, Sp. Atk, and Speed stats."),
("heal pulse",14,0,10,0,0,10,1,"The user emits a healing pulse which restores the target's HP by up to half of its max HP."),
("hex",8,50,10,0,100,10,3,"This relentless attack does massive damage to a target affected by status problems."),
("sky drop",3,60,10,0,100,10,2,"The user takes the target into the sky, then drops it during the next turn. The target cannot attack while in the sky."),
("shift gear",9,0,10,0,0,7,1,"The user rotates its gears, raising its Attack and sharply raising its Speed."),
("circle throw",2,60,10,-6,90,10,2,"The target is thrown and switched. In the wild, a battle against a single Pokémon ends."),
("incinerate",10,30,15,0,100,11,3,"The user attacks the target with fire. If the target is holding a Berry, the Berry becomes burnt up and unusable."),
("quash",17,0,15,0,100,10,1,"The user suppresses the target and makes its move go last."),
("acrobatics",3,55,15,0,100,10,2,"The user nimbly strikes the target. If the user is not holding an item, this attack inflicts massive damage."),
("reflect type",1,0,15,0,0,10,1,"The user reflects the target's type, making it the same type as the target."),
("retaliate",1,70,5,0,100,10,2,"The user gets revenge for a fainted ally. If an ally fainted in the previous turn, this attack's damage increases."),
("final gambit",2,1,5,0,100,10,3,"The user risks everything to attack its target. The user faints but does damage equal to the user's HP."),
("bestow",1,0,15,0,0,10,1,"The user passes its held item to the target when the target isn't holding an item."),
("inferno",10,100,5,0,50,10,3,"The user attacks by engulfing the target in an intense fire. It leaves the target with a burn."),
("water pledge",11,50,10,0,100,10,3,"A column of water strikes the target. When combined with its fire equivalent, the damage increases and a rainbow appears."),
("fire pledge",10,50,10,0,100,10,3,"A column of fire hits opposing Pokémon. When used with its Grass equivalent, its damage increases into a vast sea of fire."),
("grass pledge",12,50,10,0,100,10,3,"A column of grass hits opposing Pokémon. When used with its water equivalent, its damage increases into a vast swamp."),
("volt switch",13,70,20,0,100,10,3,"After making its attack, the user rushes back to switch places with a party Pokémon in waiting."),
("struggle bug",7,30,20,0,100,11,3,"While resisting, the user attacks the opposing Pokémon. The targets' Sp. Atk stat is reduced."),
("bulldoze",5,60,20,0,100,9,2,"The user stomps down on the ground and attacks everything in the area. Hit Pokémon's Speed stat is reduced."),
("frost breath",15,40,10,0,90,10,3,"The user blows a cold breath on the target. This attack always results in a critical hit."),
("dragon tail",16,60,10,-6,90,10,2,"The target is knocked away and switched. In the wild, a battle against a single Pokémon ends."),
("work up",1,0,30,0,0,7,1,"The user is roused, and its Attack and Sp. Atk stats increase."),
("electroweb",13,55,15,0,95,11,3,"The user captures and attacks opposing Pokémon by using an electric net. It reduces the targets' Speed stat."),
("wild charge",13,90,15,0,100,10,2,"The user shrouds itself in electricity and smashes into its target. It also damages the user a little."),
("drill run",5,80,10,0,95,10,2,"The user crashes into its target while rotating its body like a drill. Critical hits land more easily."),
("dual chop",16,40,15,0,90,10,2,"The user attacks its target by hitting it with brutal strikes. The target is hit twice in a row."),
("heart stamp",14,60,25,0,100,10,2,"The user unleashes a vicious blow after its cute act makes the target less wary. It may also make the target flinch."),
("horn leech",12,75,10,0,100,10,2,"The user drains the target's energy with its horns. The user's HP is restored by half the damage taken by the target."),
("sacred sword",2,90,20,0,100,10,2,"The user attacks by slicing with its long horns. The target's stat changes don't affect this attack's damage."),
("razor shell",11,75,10,0,95,10,2,"The user cuts its target with sharp shells. This attack may also lower the target's Defense stat."),
("heat crash",10,1,10,0,100,10,2,"The user slams its target with its flame- covered body. The more the user outweighs the target, the greater the damage."),
("leaf tornado",12,65,10,0,90,10,3,"The user attacks its target by encircling it in sharp leaves. This attack may also lower the target's accuracy."),
("steamroller",7,65,20,0,100,10,2,"The user crushes its targets by rolling over them with its rolled-up body. This attack may make the target flinch."),
("cotton guard",12,0,10,0,0,7,1,"The user protects itself by wrapping its body in soft cotton, drastically raising the user's Defense stat."),
("night daze",17,85,10,0,95,10,3,"The user lets loose a pitch-black shock wave at its target. It may also lower the target's accuracy."),
("psystrike",14,100,10,0,100,10,3,"The user materializes an odd psychic wave to attack the target. This attack does physical damage."),
("tail slap",1,25,10,0,85,10,2,"The user attacks by striking the target with its hard tail. It hits the target two to five times in a row."),
("hurricane",3,120,10,0,70,10,3,"The user attacks by wrapping its opponent in a fierce wind that flies up into the sky. It may also confuse the target."),
("head charge",1,120,15,0,100,10,2,"The user charges its head into its target, using its powerful guard hair. It also damages the user a little."),
("gear grind",9,50,15,0,85,10,2,"The user attacks by throwing two steel gears at its target."),
("searing shot",10,100,5,0,100,9,3,"An inferno of scarlet flames torches everything around the user. It may leave targets with a burn."),
("techno blast",1,85,5,0,100,10,3,"The user fires a beam of light at its target. The type changes depending on the Drive the user holds."),
("relic song",1,75,10,0,100,11,3,"The user sings an ancient song and attacks by appealing to the hearts of those listening. It may also induce sleep."),
("secret sword",2,85,10,0,100,10,3,"The user cuts with its long horn. The odd power contained in the horn does physical damage to the target."),
("glaciate",15,65,10,0,95,11,3,"The user attacks by blowing freezing cold air at opposing Pokémon. This attack reduces the targets' Speed stat."),
("bolt strike",13,130,5,0,85,10,2,"The user charges its target, surrounding itself with a great amount of electricity. It may leave the target with paralysis."),
("blue flare",10,130,5,0,85,10,3,"The user attacks by engulfing the target in an intense, yet beautiful, blue flame. It may leave the target with a burn."),
("fiery dance",10,80,10,0,100,10,3,"Cloaked in flames, the user dances and flaps its wings. It may also raise the user's Sp. Atk stat."),
("freeze shock",15,140,5,0,90,10,2,"On the second turn, the user hits the target with electrically charged ice. It may leave the target with paralysis."),
("ice burn",15,140,5,0,90,10,3,"On the second turn, an ultracold, freezing wind surrounds the target. This may leave the target with a burn."),
("snarl",17,55,15,0,95,11,3,"The user yells as if it is ranting about something, making the targets' Sp. Atk stat decrease."),
("icicle crash",15,85,10,0,90,10,2,"The user attacks by harshly dropping an icicle onto the target. It may also make the target flinch."),
("v create",10,180,5,0,95,10,2,"With a hot flame on its forehead, the user hurls itself at its target. It lowers the user's Defense, Sp. Def, and Speed stats."),
("fusion flare",10,100,5,0,100,10,3,"The user brings down a giant flame. This attack does greater damage when influenced by an enormous thunderbolt."),
("fusion bolt",13,100,5,0,100,10,2,"The user throws down a giant thunderbolt. This attack does greater damage when influenced by an enormous flame.")
