CREATE TABLE IF NOT EXISTS system_drawnimals (
        cuid BIGINT UNSIGNED DEFAULT 0,
        capproved TINYINT UNSIGNED DEFAULT 0,
        cimgraw TINYBLOB NOT NULL,
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	species TINYBLOB,
        form TINYINT UNSIGNED DEFAULT 0,
	type_0 TINYINT UNSIGNED,
	type_1 TINYINT UNSIGNED,
	ev_hp TINYINT,
        ev_atk TINYINT,
        ev_def TINYINT,
        ev_spatk TINYINT,
        ev_spdef TINYINT,
        ev_speed TINYINT,
	bs_hp TINYINT UNSIGNED,
	bs_atk TINYINT UNSIGNED,
	bs_def TINYINT UNSIGNED,
	bs_spatk TINYINT UNSIGNED,
	bs_spdef TINYINT UNSIGNED,
	bs_speed TINYINT UNSIGNED,
	bs_exp TINYINT UNSIGNED,
	bs_hunger TINYINT UNSIGNED,
	bs_energy TINYINT UNSIGNED,
	bs_friendship TINYINT UNSIGNED,
	rate_catch TINYINT UNSIGNED,
	rate_gender TINYINT UNSIGNED,
        rate_level TINYINT UNSIGNED,
        rate_hatch TINYINT UNSIGNED,
        script_evolve BLOB,
        script_appearance BLOB,
        script_locations BLOB,
        script_news BLOB,
	abilities BLOB,
        learnset BLOB,
	items TINYBLOB,
	description BLOB,
        description_headlines BLOB,
        description_articles BLOB,
        datetime_release INT
)
