CREATE TABLE IF NOT EXISTS user_drawnimals (
	uid BIGINT UNSIGNED,
	id BIGINT UNSIGNED AUTO_INCREMENT,
	name TINYBLOB,
	species TINYBLOB,
        paint TINYBLOB,
        form TINYINT UNSIGNED DEFAULT 0,
	move_0 TINYBLOB,
	move_1 TINYBLOB,
	move_2 TINYBLOB,
	move_3 TINYBLOB,
        move_4 TINYBLOB,
	move_pp_0 TINYINT UNSIGNED DEFAULT 0,
	move_pp_1 TINYINT UNSIGNED DEFAULT 0,
	move_pp_2 TINYINT UNSIGNED DEFAULT 0,
	move_pp_3 TINYINT UNSIGNED DEFAULT 0,
	ailments BLOB,
	ailments_default BLOB,
	st_exp SMALLINT UNSIGNED DEFAULT 0,
	st_level SMALLINT UNSIGNED DEFAULT 0,
	st_hp SMALLINT UNSIGNED DEFAULT 0,
	st_hunger SMALLINT UNSIGNED DEFAULT 32000,
	st_energy SMALLINT UNSIGNED DEFAULT 32000,
	st_friendship SMALLINT UNSIGNED,
        st_mood_datetime INT UNSIGNED,
	st_helditem TINYBLOB,
        st_partypos TINYINT DEFAULT 0,
	ev_hp SMALLINT UNSIGNED DEFAULT 0,
	ev_atk SMALLINT UNSIGNED DEFAULT 0,
	ev_def SMALLINT UNSIGNED DEFAULT 0,
	ev_spatk SMALLINT UNSIGNED DEFAULT 0,
	ev_spdef SMALLINT UNSIGNED DEFAULT 0,
	ev_speed SMALLINT UNSIGNED DEFAULT 0,
	iv_hp TINYINT UNSIGNED DEFAULT 0,
	iv_atk TINYINT UNSIGNED DEFAULT 0,
	iv_def TINYINT UNSIGNED DEFAULT 0,
	iv_spatk TINYINT UNSIGNED DEFAULT 0,
	iv_spdef TINYINT UNSIGNED DEFAULT 0,
	iv_speed TINYINT UNSIGNED DEFAULT 0,
        md_hp TINYINT DEFAULT 0,
        md_atk TINYINT DEFAULT 0,
        md_def TINYINT DEFAULT 0,
        md_spatk TINYINT DEFAULT 0,
        md_spdef TINYINT DEFAULT 0,
        md_speed TINYINT DEFAULT 0,
        md_acc TINYINT DEFAULT 0,
        md_evv TINYINT DEFAULT 0,
	origin_owner BIGINT UNSIGNED,
	origin_location TINYBLOB,
        origin_species TINYBLOB,
        origin_mama BIGINT UNSIGNED,
        origin_papa BIGINT UNSIGNED,
        info_gender TINYINT UNSIGNED,
        info_datetime_created INT UNSIGNED,
        info_obtained_datetime INT UNSIGNED,
        info_obtained_species TINYBLOB,
        info_children BLOB,
	info_awards BLOB,
        info_aboutme BLOB,
        info_ball TINYINT UNSIGNED DEFAULT 0,
        info_trading BLOB,
        info_evolving TINYBLOB,
        info_dislikes BLOB,
        info_likes BLOB,
        PRIMARY KEY (id));
